# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/15002/OneDrive/ECE212/Lab3_Ex/Lab3_ex.cache/wt [current_project]
set_property parent.project_path C:/Users/15002/OneDrive/ECE212/Lab3_Ex/Lab3_ex.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Users/15002/OneDrive/ECE212/Lab3_Ex/Lab3_ex.srcs/sources_1/new/DC.sv
  C:/Users/15002/OneDrive/ECE212/Lab3_Ex/Lab3_ex.srcs/sources_1/new/scroll_count_2.sv
  C:/Users/15002/OneDrive/ECE212/Lab3_Ex/Lab3_ex.srcs/sources_1/new/scroll_count_1.sv
  C:/Users/15002/OneDrive/ECE212/Lab3_Ex/Lab3_ex.srcs/sources_1/new/number_count.sv
  C:/Users/15002/OneDrive/ECE212/Lab3_Ex/Lab3_ex.srcs/sources_1/new/digit_generator.sv
  C:/Users/15002/OneDrive/ECE212/Lab3_Ex/Lab3_ex.srcs/sources_1/new/chooser.sv
  C:/Users/15002/OneDrive/ECE212/Lab3_Ex/Lab3_ex.srcs/sources_1/new/BRAM2.sv
  C:/Users/15002/OneDrive/ECE212/Lab3_Ex/Lab3_ex.srcs/sources_1/new/BRAM1.sv
  C:/Users/15002/OneDrive/ECE212/Lab3_Ex/Lab3_ex.srcs/sources_1/new/col_count.sv
  C:/Users/15002/OneDrive/ECE212/Lab3_Ex/Lab3_ex.srcs/sources_1/new/row_count.sv
  C:/Users/15002/OneDrive/ECE212/Lab3_Ex/Lab3_ex.srcs/sources_1/new/fsm.sv
  C:/Users/15002/OneDrive/ECE212/Lab3_Ex/Lab3_ex.srcs/sources_1/new/delay_enb.sv
  C:/Users/15002/OneDrive/ECE212/Lab3_Ex/Lab3_ex.srcs/sources_1/new/pixel_gen.sv
  C:/Users/15002/OneDrive/ECE212/Lab3_Ex/Lab3_ex.srcs/sources_1/new/sequencer.sv
  C:/Users/15002/OneDrive/ECE212/Lab3_Ex/Lab3_ex.srcs/sources_1/new/debounce.sv
  {C:/Users/15002/OneDrive/ECE212/Lab3_Ex/Lab3_ex.srcs/sources_1/new/single pulser.sv}
  C:/Users/15002/OneDrive/ECE212/Lab3_Ex/Lab3_ex.srcs/sources_1/new/LEDMatrixTopLevel.sv
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/15002/OneDrive/ECE212/Lab3/Lab3.srcs/sources_1/new/LEDMatrixConstraint.xdc
set_property used_in_implementation false [get_files C:/Users/15002/OneDrive/ECE212/Lab3/Lab3.srcs/sources_1/new/LEDMatrixConstraint.xdc]


synth_design -top LEDMatrixTopLevel -part xc7a100tcsg324-1


write_checkpoint -force -noxdef LEDMatrixTopLevel.dcp

catch { report_utilization -file LEDMatrixTopLevel_utilization_synth.rpt -pb LEDMatrixTopLevel_utilization_synth.pb }
